export { default as Navbar } from './Navbar/Navbar';
export { default as Footer } from './Footer/Footer';
export { default as HeroSection } from './HeroSection/HeroSection';
export { default as FAQSection } from './FAQSection/FAQSection';
export { default as About } from './AboutSection/About';
export { default as Ticker } from './HeroSection/Ticker';
export { default as EventSection } from './Events/EventSection';
export { default as RegistrationForm } from './RegistrationForm/RegistrationForm';
export { default as ProfileSection } from './ProfileSection/ProfileSection';
